services:
  - type: web
    name: book2audio
    runtime: docker
    plan: free
    rootDir: book2audio
    envVars:
      - key: TURSO_DB_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        value: book2audio
